export const stories = [
  {
    id: '00100',
    title: '本宮要上位',
    subtitle: '「呸、通俗才是王道，吾就不信吾選的《愛如火》一定會輸!」',
    content: '昏黃的日光越過簷角，瀉在光滑的青石路上。\n\n書局、古董鋪和裱畫店林立在街道兩側，\n\n染著墨香的門幌在風裡輕晃。\n\n國子監和私塾都放了學，\n\n穿著各色長衫的書生們執著書卷，說笑著,，結伴著行在這條素有“文人寶地”之稱的正街上.......\n\n乍一看，彷彿不過是這大清國再平常不過的一幅景象。\n\n直到轎子湊近，那些書生的談笑映入你的耳畔—————\n\n「南湘忘恩負義，蛇蠍心腸，白瞎吾家顧裡對她那麼好!李兄,你若再敢在學堂上為這毒婦辯言,你我的情誼,也是時候斷絕了!」\n\n「愛你孤身走暗巷,愛你不跪的模樣!哼,先生們皆言,這首 《孤勇者》音律俱佳,詞意深遠,誰若通會其中風韻,今年科舉的頭籌,八成就是他了......」\n\n「呸,通俗才是王道,吾就不信吾選的《愛如火》一定會輸!」\n\n這一切瘋狂的改變，都得從眾人口中的那位太監國師，九千歲王德發說起。',
    price: 690,
    star: 2,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["歡樂搞笑", "機制陣營"],
    people: [8],
    words: 20000,
    time: `5-6 hr.`,
    cloth: '全換裝',
    type: 0, //1新本, 2城限
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },
  {
    id: '00101',
    title: '二流貨色',
    subtitle: '「瘋子的墓誌銘上寫滿愛情」',
    content: '我洞悉你靈魂的每一寸荒蕪與平庸，然而我依然愛你。\n\n我預見你路途的每一處荊棘與深淵，然而我依然愛你。\n\n我深知這迷戀是自毀的淵藪，我甘願背負世人的謳諷與唾棄，\n\n在荒唐的廢墟上，可我依然愛你。\n\n我像個不識時務的愚者安息於此，\n\n我以荊棘為冠冕，深淵作溫床，\n\n墓碑上刻著—\n\n我明知是幻影，可我依然愛你。',
    price: 590,
    star: 2,
    cover: require('../assets/images/stories/00101/cover.png'),
    tag: ["情感沈浸", "真相還原"],
    people: [6],
    words: 25000,
    time: `4-5 hr.`,
    cloth: '無',
    type: 1,
    characters:[
      {
        name: '24幀',
        charTag: '男',
        image: require('../assets/images/stories/00101/ch1.png'),
      },
      {
        name: '燕尾蝶',
        charTag: '女',
        image: require('../assets/images/stories/00101/ch2.png'),
      },
      {
        name: '壞血',
        charTag: '男',
        image: require('../assets/images/stories/00101/ch3.png'),
      },
      {
        name: '笨金魚',
        charTag: '女',
        image: require('../assets/images/stories/00101/ch4.png'),
      },
      {
        name: '白河夜船',
        charTag: '男',
        image: require('../assets/images/stories/00101/ch5.png'),
      },
      {
        name: '鏽與骨',
        charTag: '女',
        image: require('../assets/images/stories/00101/ch6.png'),
      },
    ],
  },
  {
    id: '00102',
    title: '兇手的小酒酒',
    subtitle: '喝',
    content: '想讀本\n\n兄弟，你聽我說。\n\n嗝~\n\n我跟你講，兇手就是......\n\n嗝~\n\n你先別管什麼邏輯不邏輯。\n\n嗝~\n\n我真沒喝多!\n\n算了，兇手愛是誰就是誰！',
    price: 590,
    star: 4,
    cover: require('../assets/images/stories/00102/cover.jpg'),
    tag: ["真相還原", "歡樂搞笑"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '印度淡色艾爾啤酒',
        charTag: '男',
        image: require('../assets/images/stories/00102/ch1.png'),
      },
      {
        name: '荔枝接骨木西打啤酒',
        charTag: '女',
        image: require('../assets/images/stories/00102/ch2.png'),
      },
      {
        name: '美式大麥拉格啤酒',
        charTag: '男',
        image: require('../assets/images/stories/00102/ch3.png'),
      },
      {
        name: '蛇毒啤酒',
        charTag: '女',
        image: require('../assets/images/stories/00102/ch4.png'),
      },
      {
        name: '香草牛奶巧克力世濤啤酒',
        charTag: '男',
        image: require('../assets/images/stories/00102/ch5.png'),
      },
      {
        name: '車厘子檸檬皮酸啤酒',
        charTag: '女',
        image: require('../assets/images/stories/00102/ch6.png'),
      },
    ],
  },
  {
    id: '00103',
    title: '血腥愛情故事',
    subtitle: '我如玫瑰，背光而長……',
    content: '2000年5月，千禧之夏，\n\n六起詭異的命案接連發生，震動江城，六名死者，皆來自於江城一中。\n\n他們彼此間的故事，令人瞠目結舌......\n\n2025年，一款名為《千禧年的愛戀2》的互動式夢核遊戲橫空出世，\n\n而遊戲的內容卻似乎與千禧年連環命案，有著千絲萬縷的聯繫？\n\n可疑的暱稱，奇怪的聊天室， 疑竇叢生的命案，危機四伏的遊戲......\n\n穿越夢境深處的千禧年，\n\n摘下愛與仇恨的一束，模糊記憶中的玫瑰，正逆光盛開......',
    price: 690,
    star: 2,
    cover: require('../assets/images/stories/00103/cover.png'),
    tag: ["真相還原", "演繹沈浸"],
    people: [6],
    words: 4000,
    time: `5-6 hr.`,
    cloth: '無',
    type: 1,
    characters:[
      {
        name: '橡皮泥',
        charTag: '「任憑你拿捏。」',
        image: require('../assets/images/stories/00103/ch1.png'),
      },
      {
        name: '沙畫',
        charTag: '「美術生比醫生更懂人體。」',
        image: require('../assets/images/stories/00103/ch2.png'),
      },
      {
        name: '玻璃彈珠',
        charTag: '「小心，別碎了。」',
        image: require('../assets/images/stories/00103/ch3.png'),
      },
      {
        name: '綠豆冰沙',
        charTag: '「我是真渴了。」',
        image: require('../assets/images/stories/00103/ch4.png'),
      },
      {
        name: '磁帶',
        charTag: '「好聽到懷孕了。」',
        image: require('../assets/images/stories/00103/ch5.png'),
      },
      {
        name: '花繩',
        charTag: '「我喜歡另一種綑綁。」',
        image: require('../assets/images/stories/00103/ch6.png'),
      },
    ],
  },
  {
    id: '00104',
    title: '二手名著',
    subtitle: '「致尚未誕生的，真正的讀者。」',
    content: '「一手的名著早已脫離潮流，二手的名著才能博人眼球！」\n\n「我從業十年，如今終於找到了流量密碼哈哈哈～」\n\n「......可惡，難道就沒人能懂得我作品的精妙嗎！不過我相信那只是他們手下庸人的刁難......」\n\n「對了對了，如果是他們本人一定可以！」\n\n【新書預告】《二手名著》\n\n從業十年的新人作家，貫穿書海的巧妙組合。\n\n這才是當代讀者要的文藝復興！\n\n新書發售首日，萬人空巷，銷量破百萬！\n\n「我敢肯定，當我的作品真正發售的那天！一定會是這樣。」',
    price: 590,
    star: 4,
    cover: require('../assets/images/stories/00104/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '屍魔',
        charTag: '「倒亂陰陽，多造口業」',
        image: require('../assets/images/stories/00104/ch1.png'),
      },
      {
        name: '水怪',
        charTag: '「吃人無算，強佔洞府」',
        image: require('../assets/images/stories/00104/ch2.png'),
      },
      {
        name: '沙彌',
        charTag: '「欺師滅祖，蠱惑眾人」',
        image: require('../assets/images/stories/00104/ch3.png'),
      },
      {
        name: '童子',
        charTag: '「偷盜寶物，佔城為王」',
        image: require('../assets/images/stories/00104/ch4.png'),
      },
      {
        name: '道人',
        charTag: '「謀奪金銀，謀財害命」',
        image: require('../assets/images/stories/00104/ch5.png'),
      },
      {
        name: '鼍龍',
        charTag: '「仗勢害人，愚弄世人」',
        image: require('../assets/images/stories/00104/ch6.png'),
      },
    ],
  },
  {
    id: '00105',
    title: '案件預演',
    subtitle: '「歡樂直播飆戲，奧斯卡等你拿！」',
    content: '2026年「神探儀」問世，\n\n神奇的功能讓世界各地的警察機構不再負責處理命案，\n\n轉而交給了配合神探儀偵破命案的「罪演師」，\n\n在兩者的配合下犯罪率急劇下降，\n\n同时也出現了「逃脱者」，他們幫助凶手逃脱抓捕。\n\n一檔由「逃脱者」主辦的地下真人直播推理秀在黑暗中悄然誕生，名為——「案件預演」。',
    price: 690,
    star: 3,
    cover: require('../assets/images/stories/00105/cover.png'),
    tag: ["歡樂搞笑", "真相還原", "刑偵緝兇"],
    people: [6],
    words: 5000,
    time: `5-6 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '罪演師A',
        charTag: null,
        image: require('../assets/images/stories/00105/ch1.jpg'),
      },
      {
        name: '罪演師B',
        charTag: null,
        image: require('../assets/images/stories/00105/ch2.jpg'),
      },
      {
        name: '罪演師C',
        charTag: null,
        image: require('../assets/images/stories/00105/ch3.jpg'),
      },
      {
        name: '罪演師D',
        charTag: null,
        image: require('../assets/images/stories/00105/ch4.jpg'),
      },
      {
        name: '罪演師E',
        charTag: null,
        image: require('../assets/images/stories/00105/ch5.jpg'),
      },
      {
        name: '罪演師F',
        charTag: null,
        image: require('../assets/images/stories/00105/ch6.jpg'),
      },
    ],
  },
  {
    id: '00106',
    title: '牛鬼蛇神',
    subtitle: '「給我幹那兒來了，什麼牛鬼蛇神！」',
    content: '民國初年，城中最大的宅子被一位神秘的官老爺買下，\n\n並重新提名「孽宅」，可「孽宅」之中十分不太平，\n\n先是家裡頻頻有怪事發生，\n\n現在就連他最愛的夫人都中了邪。\n\n這天，一位道士打扮的人敲開了「孽宅」的大門\n\n而這詭異「孽宅」中的一切真相，\n\n還要從宅子中的突然牛斃事件開始說起……',
    price: 490,
    star: 2,
    cover: require('../assets/images/stories/00106/cover.png'),
    tag: ["歡樂搞笑", "真相還原", "新手入門"],
    people: [5],
    words: 4000,
    time: `2-3 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '道士',
        charTag: '男',
        image: require('../assets/images/stories/00106/ch1.png'),
      },
      {
        name: '老爺',
        charTag: '男',
        image: require('../assets/images/stories/00106/ch2.png'),
      },
      {
        name: '管家',
        charTag: '男',
        image: require('../assets/images/stories/00106/ch3.png'),
      },
      {
        name: '夫人',
        charTag: '女',
        image: require('../assets/images/stories/00106/ch4.png'),
      },
      {
        name: '二姨太',
        charTag: '女',
        image: require('../assets/images/stories/00106/ch5.png'),
      },
    ],
  },
  {
    id: '00107',
    title: '我的朋友是一具會說話的屍體',
    subtitle: '朋友們，遊戲開始了：）',
    content: '我手上的，這是什麼？是繩索嗎？\n\n為什麼，我什麼都記不起來了。\n\n身體各個部位傳來陣痛，眼前是個陰暗潮濕的房間，什麼都看不見。\n\n我沒聽錯嗎？有別人的喘息聲，這個房間裡，還有別人？\n\n正當我想發出詢問時，鐵門打開的聲音打斷了我。\n\n燈亮起來了，是一個瘦弱的男人，帶著詭異的笑容站在大門前看著我，\n\n喔不，是我們。\n\n「歡迎，來到我的遊戲，我的朋友們。」他這麼說道。\n\n隨即便是無盡的譏笑聲……',
    price: 890,
    star: 4,
    cover: require('../assets/images/stories/00107/cover.png'),
    tag: ["真相還原","推理緝兇","城市限定"],
    people: [6],
    words: 12000,
    time: `5-6 hr.`,
    cloth: '無',
    type: 2,
    characters:[
      {
        name: 'A',
        charTag: '女。',
        image: require('../assets/images/stories/00107/ch1.png'),
      },
      {
        name: 'B',
        charTag: '男。',
        image: require('../assets/images/stories/00107/ch2.png'),
      },
      {
        name: 'C',
        charTag: '男。',
        image: require('../assets/images/stories/00107/ch3.png'),
      },
      {
        name: 'D',
        charTag: '女。',
        image: require('../assets/images/stories/00107/ch4.png'),
      },
      {
        name: 'E',
        charTag: '男。',
        image: require('../assets/images/stories/00107/ch5.png'),
      },
      {
        name: 'F',
        charTag: '男。',
        image: require('../assets/images/stories/00107/ch6.png'),
      },
    ],
  },
  {
    id: '00108',
    title: '世紀末的最後一場雪',
    subtitle: '「昨日種種昨日死，未來之事不可期」',
    content: '男人手裡拿著七份邀請函，\n\n走走停停，每在一個地方停留，\n\n手中的邀請函就會少上一些。\n\n男人走出小鎮，踏入群山之中，\n\n帶著最後一封邀請函，來到了山間的一個別墅。\n\n他熟悉地打開了別墅院子大門，\n\n走到別墅窗邊，將邀請函扔了進去。\n\n隨後，他返回了院子大門處，靜靜地等待著……',
    price: 590,
    star: 2,
    cover: require('../assets/images/stories/00108/cover.png'),
    tag: ["真相還原", "情感沈浸"],
    people: [7],
    words: 38000,
    time: `3-4 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '小玉',
        charTag: '女，活潑可愛的少女，文南鎮的小學老師。',
        image: require('../assets/images/stories/00108/ch1.png'),
      },
      {
        name: '李煙',
        charTag: '女，臉上有疤痕的中年女人，文南鎮孤兒院院長。',
        image: require('../assets/images/stories/00108/ch2.png'),
      },
      {
        name: '梁平',
        charTag: '男，身穿醫師袍的中年男人，享譽世界的物理學家。',
        image: require('../assets/images/stories/00108/ch3.png'),
      },
      {
        name: '磊磊',
        charTag: '男，健壯的少年，文南鎮的警察。',
        image: require('../assets/images/stories/00108/ch4.png'),
      },
      {
        name: '趙董',
        charTag: '男，戴眼鏡的中年男人，全球首富。',
        image: require('../assets/images/stories/00108/ch5.png'),
      },
      {
        name: '錢康',
        charTag: '男，西裝革履的中年男人，趙董助手。',
        image: require('../assets/images/stories/00108/ch6.png'),
      },
      {
        name: '阿東',
        charTag: '男，瘦弱的少年，裝修隊的工人。',
        image: require('../assets/images/stories/00108/ch7.png'),
      },
    ],
  },
  {
    id: '00109',
    title: '坐牢的超能者殺人日常',
    subtitle: '喂喂喂，別在監獄裡搞謀殺阿！',
    content: '超能監獄最近迎來了新的一批超能者罪犯，\n\n大家聚在303室聊天、喝酒、說大話……\n\n但沒想到的是，\n\n在未來的24小時裡，\n\n超能監獄內竟發生了三起凶案……',
    price: 490,
    star: 2,
    cover: require('../assets/images/stories/00109/cover.png'),
    tag: ["新手入門", "推理緝兇"],
    people: [5],
    words: 4000,
    time: `2-3 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '光能小子',
        charTag: '男。',
        image: require('../assets/images/stories/00109/ch1.png'),
      },
      {
        name: '波濤小子',
        charTag: '男。',
        image: require('../assets/images/stories/00109/ch2.png'),
      },
      {
        name: '草帽小子',
        charTag: '男。',
        image: require('../assets/images/stories/00109/ch3.png'),
      },
      {
        name: '護額小子',
        charTag: '男。',
        image: require('../assets/images/stories/00109/ch4.png'),
      },
      {
        name: '頭盔小子',
        charTag: '男。',
        image: require('../assets/images/stories/00109/ch5.png'),
      },
    ],
  },
  {
    id: '00110',
    title: '沉默少女的溫柔暴動',
    subtitle: '愛情的本質，大概是一些月亮和心碎。',
    content: '愛是什麼？\n\n炙熱狂喊的自毀、默念萬遍的名字、街角撐起的雨傘、\n\n反覆掀起的傷疤，這些都是愛，卻也只是愛的一小部分。\n\n它們不過，是看不清的世界與內耗的自己，\n\n是現實對想象的撕裂，是溫柔暴動的擱淺回憶。\n\n我想，這個無比龐大的命題，\n\n對於小小的我們來說，或許根本沒有意義。',
    price: 590,
    star: 2,
    cover: require('../assets/images/stories/00110/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 16000,
    time: `3-4 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '吳憂',
        charTag: '女。',
        image: require('../assets/images/stories/00110/ch1.png'),
      },
      {
        name: '唐霜',
        charTag: '女。',
        image: require('../assets/images/stories/00110/ch2.png'),
      },
      {
        name: '喬熙',
        charTag: '女。',
        image: require('../assets/images/stories/00110/ch3.png'),
      },
      {
        name: '徐行',
        charTag: '男。',
        image: require('../assets/images/stories/00110/ch4.png'),
      },
      {
        name: '江楚辭',
        charTag: '男。',
        image: require('../assets/images/stories/00110/ch5.png'),
      },
      {
        name: '詩施',
        charTag: '女。',
        image: require('../assets/images/stories/00110/ch6.png'),
      },
    ],
  },
  {
    id: '00111',
    title: '海是一場雨',
    subtitle: '從那以後，人們便將「雨」看作倒著的海⋯⋯',
    content: '每個徘徊在洛神鄉的人，都是倒放的煙花，靜默中綻放，逆流裡追尋。/n這片天地，如詩如歌，承載著遺憾與希望，綺麗依然。/n直到有一天，大海和火焰都從地圖上消失了。/n從那以後，人們便將「雨」——看作倒著的海。',
    price: 690,
    star: 3,
    cover: require('../assets/images/stories/00111/cover.png'),
    tag: ["真相還原", "情感沈浸"],
    people: [6],
    words: 45000,
    time: `5-6 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '裊裊',
        charTag: '女，「我們不是糾纏的藤蔓，是變量和永恆，只能停留在對岸。」',
        image: require('../assets/images/stories/00111/ch1.png'),
      },
      {
        name: '團團',
        charTag: '女，「世界總有一個地方可以讓我們藏起來，就我和你。」',
        image: require('../assets/images/stories/00111/ch2.png'),
      },
      {
        name: '蝶衣',
        charTag: '女，「如果可以，我寧願飛蛾撲火。」',
        image: require('../assets/images/stories/00111/ch3.png'),
      },
      {
        name: '小野',
        charTag: '男，「直到我變成一潭死水，你是我掌心僅有的船。」',
        image: require('../assets/images/stories/00111/ch4.png'),
      },
      {
        name: '瑾瑜',
        charTag: '男，「別看我，你會發現我的謊言不完整。」',
        image: require('../assets/images/stories/00111/ch5.png'),
      },
      {
        name: '阿焰',
        charTag: '男，「為你殺出一片自由之地，我在灰燼之中愛你。」',
        image: require('../assets/images/stories/00111/ch6.png'),
      },
    ],
  },
  {
    id: '00112',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 1,
    cover: require('../assets/images/stories/00112/cover.png'),
    tag: ["機制陣營", "歡樂搞笑"],
    people: [7],
    words: 15000,
    time: `5-6 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '宮碩',
        charTag: '男，60歲。\n\n「歷經歲月沉澱的菸酒商老闆。」',
        image: require('../assets/images/stories/00112/ch1.png'),
      },
      {
        name: '張巨帥',
        charTag: '男，23歲。\n\n「世界上最帥的男孩。」',
        image: require('../assets/images/stories/00112/ch2.png'),
      },
      {
        name: '李猜',
        charTag: '男，23歲。\n\n「文質彬彬的男孩。」',
        image: require('../assets/images/stories/00112/ch3.png'),
      },
      {
        name: '楊肉串',
        charTag: '男，48歲。\n\n「憨厚老實、勤勞的燒烤店老闆。」',
        image: require('../assets/images/stories/00112/ch4.png'),
      },
      {
        name: '楊娃娃',
        charTag: '女，23歲。\n\n「心地善良、衣著純樸的美麗農村女孩。」',
        image: require('../assets/images/stories/00112/ch5.png'),
      },
      {
        name: '陸雨萱',
        charTag: '女，24歲。\n\n「心地善良、長相甜美的女主播。」',
        image: require('../assets/images/stories/00112/ch6.png'),
      },
      {
        name: '龍詩穎',
        charTag: '女，24歲。\n\n「傾國傾城的金髮女孩。」',
        image: require('../assets/images/stories/00112/ch7.png'),
      },
    ],
  },
  {
    id: '00113',
    title: '野狗不需要墓碑',
    subtitle: '我曾經死去的我，要殺死現在活著的我⋯⋯',
    content: '在小鎮裡發生了一起慘案，它交織著背叛、猜疑、血腥。\n\n最不可直視的，是那最親之人舉起的殺戮之刃。\n\n有一家六口，出現了一個瘋子，它用自己的命，將全家屠殺，完成了這場無人生還。\n\n是什麼原因，讓一個人將自己的親人盡數殺死？\n\n背後的真相，令人毛骨悚然毛骨悚然⋯⋯',
    price: 590,
    star: 3,
    cover: require('../assets/images/stories/00113/cover.png'),
    tag: ["演繹沈浸", "真相還原"],
    people: [6],
    words: 9000,
    time: `4-5 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '方八更',
        charTag: '爺爺，「還要熬過多少分裂自愈的夜晚，我才能得到解脫。」',
        image: require('../assets/images/stories/00113/ch1.png'),
      },
      {
        name: '方　平',
        charTag: '爸爸，「雲霧彌散之際，我愛你，人盡皆知。」',
        image: require('../assets/images/stories/00113/ch2.png'),
      },
      {
        name: '崔　敏',
        charTag: '媽媽，「不周旋，寧做我。」',
        image: require('../assets/images/stories/00113/ch3.png'),
      },
      {
        name: '方　明',
        charTag: '哥哥，「我是躲在黑裡的老鼠，扭曲如蛀蟲。」',
        image: require('../assets/images/stories/00113/ch4.png'),
      },
      {
        name: '方　櫻',
        charTag: '妹妹，「願世間所有的愛，都被善待。」',
        image: require('../assets/images/stories/00113/ch5.png'),
      },
      {
        name: '方　蔓',
        charTag: '姊姊，「你毀滅了我，我要你活著，接受我的毀滅。」',
        image: require('../assets/images/stories/00113/ch6.png'),
      },
    ],
  },
  {
    id: '00114',
    title: '艾希什影院：無人循環',
    subtitle: '預言者之所以神秘，是因為他願意潛入深空的夢境⋯⋯',
    content: '六位觀影者落座，螢幕逐漸亮起，四部電影昭示著四起神秘詭誦的無人生還案件，伴隨這場叫做浮影溯夢的觀影會，拉開序幕。\n\n空氣之中似乎能夠嗅到一絲歲月腐蝕的痕跡，斑駁的木門吱呀幾聲，簌簌風聲裹挾著塵埃，凝聚成一個斗篷的模樣，似乎是一位老者，以幽靈一般的姿態注視著六位觀影者。\n\n濱海閣樓、六角建築、神秘村落、孤獨島嶼，這場充斥著幻想與血腥的詭異旅程，卻隱藏著名為「無人循環」的秘密終章。\n\n歡迎各位來到——艾希什影院。\n\n待播影片：盲人影院、人生海海、燈塔水母、黃金原野⋯⋯',
    price: 890,
    star: 5,
    cover: require('../assets/images/stories/00114/cover.png'),
    tag: ["城市限定", "真相還原", "硬核推理"],
    people: [6],
    words: 15000,
    time: `5-6 hr.`,
    cloth: '無',
    type: 2,
    characters:[
      {
        name: '？？？',
        charTag: null,
        image: require('../assets/images/stories/00114/ch1.png'),
      },
      {
        name: '？？？',
        charTag: null,
        image: require('../assets/images/stories/00114/ch2.png'),
      },
      {
        name: '？？？',
        charTag: null,
        image: require('../assets/images/stories/00114/ch3.png'),
      },
      {
        name: '？？？',
        charTag: null,
        image: require('../assets/images/stories/00114/ch4.png'),
      },
      {
        name: '？？？',
        charTag: null,
        image: require('../assets/images/stories/00114/ch5.png'),
      },
      {
        name: '？？？',
        charTag: null,
        image: require('../assets/images/stories/00114/ch6.png'),
      },
    ],
  },
  {
    id: '00115',
    title: '致命巧克力',
    subtitle: '一樁血案、一場爆炸、通往天堂的「天堂酒店」⋯⋯',
    content: '世界博覽會即將在巴黎召開，全美知名的邦加兄弟巧克力公司，將在博覽會期間推出最新的巧克力——「爆蛋」。\n\n然而，博覽會還沒開始，邦加兄弟巧克力公司的老闆——比利．邦加，卻離奇死在巴黎最豪華的「天堂酒店」裡⋯⋯',
    price: 490,
    star: 2,
    cover: require('../assets/images/stories/00115/cover.png'),
    tag: ["新手入門", "推理緝兇"],
    people: [8, 14],
    words: 3500,
    time: `3-4 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '伯特蘭 Bertrand',
        charTag: '穩重，嚴謹，高貴，傳奇巧克力公司總裁。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '芭芭拉 Barbara',
        charTag: '高調自負，穿著華麗，浪漫主義小說作家。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '杜莎姆 Ducharme',
        charTag: '崇尚自由，外表美麗，前衛的雕塑藝術家。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '朵麗絲 Doris',
        charTag: '孤僻，崇拜信仰，執著的考古學博士。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '利特爾 Littell',
        charTag: '焦慮，技藝高超，著名的木偶腹語師。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '瑪莉亞 Maria',
        charTag: '堅毅，精明幹練，年輕的甘椰巧克力公司總裁。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '泰森 Tyson',
        charTag: '熱愛運動，身體素質強，好運的拳擊運動員。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '弗洛伊德 Freud',
        charTag: '冷靜，觀察力強，洞察人心的心理學家。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '丹尼爾 Daniel',
        charTag: '膽小，怕麻煩，喜歡拳擊的酒吧服務生。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '瑪格麗特 Margaret',
        charTag: '謹慎，喜歡旅遊，好奇的外國遊客。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '拉爾夫 Ralph',
        charTag: '幹練，不擅言詞，身份未知的神秘男子。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '尼可拉斯 Nicolas',
        charTag: '沉穩親和，聰明的小學老師。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '威廉 William',
        charTag: '行動力強，努力負責，邦加的助理。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
      {
        name: '海克力斯 Hercules',
        charTag: '聰明，細緻入微，大名鼎鼎的偵探。',
        image: require('../assets/images/stories/00115/ch1.png'),
      },
    ],
  },
  {
    id: '00116',
    title: '匯通天下',
    subtitle: '晉商之成功，在於眾，聚眾為勢，聚商為富⋯⋯',
    content: '晉南一帶地窄人稠，外出經商成為當地百姓的謀生之道，待到明清年間，晉商已遍及各地。\n\n故有言道：「京師大賈數晉人。」\n\n晉商之成功，在於眾，聚眾為勢，聚商為富。\n\n道光元年，山西五大晉商共組聚商會，因咸福鹽鋪資金最為豐厚，其東家康澤被推選為首任會長。\n\n至道光四年，康家因私鑄官銀被抄家滅門，聚商會受此牽，連名存實亡，喬、常、曹、王四家紛紛避嫌，各自經營。\n\n道光十五年，地方賊寇猖狂，貨物運轉困難，山西四大富商決意共赴北京城，重組聚商會，以商討對策。\n\n巧的是，現下的四大富商亦是當年的聚商會成員，日昌顏料鋪喬氏、泰豐茶鋪常氏、裕和藥鋪曹氏和同慶鹽鋪王氏。\n\n四家各出代表，將從中選出新任會長。',
    price: 590,
    star: 2,
    cover: require('../assets/images/stories/00116/cover.png'),
    tag: ["機制陣營", "歡樂搞笑"],
    people: [16, 20],
    words: 1200,
    time: `4-5 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '喬　義',
        charTag: '男，日昌顏料鋪少東家。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '雷　候',
        charTag: '男，日昌顏料鋪掌櫃。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '喬　悅',
        charTag: '女，日昌顏料鋪帳房。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '葉　來',
        charTag: '女，日昌顏料鋪幫工。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '常　德',
        charTag: '男，泰豐茶鋪東家。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '常　仁',
        charTag: '男，泰豐茶鋪掌櫃。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '周　平',
        charTag: '男，泰豐茶鋪帳房。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '瑪　麗',
        charTag: '女，泰豐茶鋪少奶奶。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '曹遇禮',
        charTag: '男，裕和藥鋪東家。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '曹益民',
        charTag: '男，裕和藥鋪曹氏掌櫃。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '柳　菁',
        charTag: '女，裕和藥鋪曹氏帳房。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '柳　軒',
        charTag: '男，裕和藥鋪曹氏幫工。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '王　茹',
        charTag: '女，同慶鹽鋪東家。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '趙　信',
        charTag: '男，同慶鹽鋪掌櫃。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '孫　凱',
        charTag: '男，同慶鹽鋪帳房。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '王　晏',
        charTag: '男，同慶鹽鋪幫工。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '鄭　薔',
        charTag: '女，門客。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '顏如玉',
        charTag: '女，門客。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '關太虛',
        charTag: '男，門客。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
      {
        name: '時運轉',
        charTag: '女，門客。',
        image: require('../assets/images/stories/00116/ch1.png'),
      },
    ],
  },
  {
    id: '00117',
    title: '側寫師',
    subtitle: '我們尊重這世界上的正義，亦是要保護這世界上的美好⋯⋯',
    content: '這個故事的開始，只是一通奇怪的報警電話。\n\n這個故事的結束，是他留給我的一封遺書。\n\n除了沈默不語，再點上一根菸外，我真的不知道，該去找誰訴說。\n\n「這封遺書裡，有我希望你幫我做的最後一件事⋯⋯」',
    price: 590,
    star: 3,
    cover: require('../assets/images/stories/00117/cover.png'),
    tag: ["真相還原", "刑偵緝兇"],
    people: [4, 50],
    words: 5000,
    time: `3-4 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '刑偵隊學習報告',
        charTag: null,
        image: require('../assets/images/stories/00100/ch1.png'),
      },
    ],
  },
  {
    id: '00118',
    title: '我超能推理',
    subtitle: '我相信，我們超能推理的！',
    content: '全家都有超能力，唯獨我沒有！\n\n啊啊啊家人們，我好痛，我好苦！\n\n我化悲憤為靈感，猛猛寫了兩個天謎天解的本格案件，\n\n審稿編輯卻說：\n\n「都什麼年代了，還在抽傳統本格？食大便了，大人，設定系懂嗎？設定系！」\n\n舌釘系？啥玩意兒？聽都沒聽過......\n\n等等，我不是還有親愛的你們嘛！\n\n大我一百歲的老公，還有八十多歲的爸爸，你們作為超能者，就幫幫我續寫這部失敗的推理小說吧！',
    price: 490,
    star: 3,
    cover: require('../assets/images/stories/00118/cover.png'),
    tag: ["歡樂搞笑"],
    people: [4, 5],
    words: 3000,
    time: `2-3 hr.`,
    cloth: '無',
    type: 1,
    characters:[
      {
        name: '爺爺',
        charTag: '「曾有一份真摯的感情擺在我的面前，而我沒能珍惜。」',
        image: require('../assets/images/stories/00118/ch1.png'),
      },
      {
        name: '爸爸',
        charTag: '「他愛而不可得，我也是。」',
        image: require('../assets/images/stories/00118/ch2.png'),
      },
      {
        name: '孫女',
        charTag: '「有些愛情可以跨越一切。」',
        image: require('../assets/images/stories/00118/ch3.png'),
      },
      {
        name: '哥們',
        charTag: '「他的存在無可替代，長得再像也不行。」',
        image: require('../assets/images/stories/00118/ch4.png'),
      },
      {
        name: '同學',
        charTag: '「只因起跑線上慢了一步，我的人生就被竊取了。」',
        image: require('../assets/images/stories/00118/ch5.png'),
      },
    ],
  },
  {
    id: '00119',
    title: '加個賴唄',
    subtitle: '當年冠希哥維修電腦，竟爆出不雅影片，如今你撿到手機，竟破了懸案？',
    content: '家人們誰懂啊！！！\n\n我撿到了四部手機，未曾想聊天記錄如此勁爆！\n\n小帥儀表堂堂，暗地裡竟在Keep發那些玩意兒？\n\n小美高冷獨美，卻在IG限動狂撩異性？\n\n這都算了，問題是——\n\n怎麼還會有人將犯罪自白傳上賴啊？\n\n歡樂！吃瓜！推理囉～～～\n\n你能摸清他們的八卦嗎？',
    price: 490,
    star: 2,
    cover: require('../assets/images/stories/00119/cover.png'),
    tag: ["真相還原"],
    people: [4],
    words: 1000,
    time: `2-3 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: 'Kelvin陌西',
        charTag: null,
        image: require('../assets/images/stories/00119/ch1.png'),
      },
      {
        name: 'Annie.',
        charTag: null,
        image: require('../assets/images/stories/00119/ch2.png'),
      },
      {
        name: '備課漢墓',
        charTag: null,
        image: require('../assets/images/stories/00119/ch3.png'),
      },
      {
        name: '雙眼一閉，六親不認',
        charTag: null,
        image: require('../assets/images/stories/00119/ch4.png'),
      },
    ],
  },
  {
    id: '00120',
    title: '猛鬼大廈HAHAHA',
    subtitle: '鬼上身？鬼打牆？鬼遮眼？傻傻分不清楚⋯⋯',
    content: '20世紀80年代末，香港燦爛繁榮，白天充斥著紙醉金迷，夜晚燈火通明，彷彿是個不夜城。\n\n就在這樣一座繁華都市裡，卻有一處被稱為「魔窟」的猛鬼大廈，這裡生活環境十分惡劣，充滿了人性的骯髒，怪事頻發搞得住戶不得安寧，裡面的人拼了命的想逃出去，但是迫於生計不得不留在這裡。\n\n如今猛鬼大廈即將拆除，卻有一群不怕死的年輕人偏要進來，午夜鐘聲響起，周遭的環境變得壓抑且詭異，你們是在找我嗎？',
    price: 590,
    star: 3,
    cover: require('../assets/images/stories/00120/cover.png'),
    tag: ["恐怖驚悚", "歡樂搞笑", "真相還原"],
    people: [7],
    words: 8000,
    time: `4-5 hr.`,
    cloth: '無',
    type: 0,
    characters:[
      {
        name: '301 / 輝仔',
        charTag: null,
        image: require('../assets/images/stories/00120/ch1.png'),
      },
      {
        name: '302 / 細狗',
        charTag: null,
        image: require('../assets/images/stories/00120/ch2.png'),
      },
      {
        name: '303 / 雄哥',
        charTag: null,
        image: require('../assets/images/stories/00120/ch3.png'),
      },
      {
        name: '304 / 阿耀',
        charTag: null,
        image: require('../assets/images/stories/00120/ch4.png'),
      },
      {
        name: '305 / 阿May',
        charTag: null,
        image: require('../assets/images/stories/00120/ch5.png'),
      },
      {
        name: '306 / 囡囡',
        charTag: null,
        image: require('../assets/images/stories/00120/ch6.png'),
      },
      {
        name: '307 / 雨珊',
        charTag: null,
        image: require('../assets/images/stories/00120/ch7.png'),
      },
    ],
  },

  {
    id: '00121',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 4,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },

  {
    id: '00122',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 4,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },

  {
    id: '00123',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 4,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },

  {
    id: '00124',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 4,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },

  {
    id: '00125',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 4,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },

  {
    id: '00126',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 4,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },

  {
    id: '00127',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 4,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },

  {
    id: '00128',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 4,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },

  {
    id: '00129',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 4,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },

  {
    id: '00130',
    title: '碰瓷兒',
    subtitle: '啊……疼……快來人，出人命啦！',
    content: '三百六十行，行行出狀元，\n\n這碰瓷兒一行始於明清，盛於當下；\n\n這日，老者神情痛苦地躺在青年人的車輪前。\n\n究竟是青年撞人在先？還是老者惡意碰瓷兒？\n\n一齣好戲正在上演……',
    price: 690,
    star: 4,
    cover: require('../assets/images/stories/00100/cover.png'),
    tag: ["真相還原"],
    people: [6],
    words: 10000,
    time: `4-5 hr.`,
    cloth: '全換裝',
    type: 0,
    characters:[
      {
        name: '愛新覺羅帥',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch1.png'),
      },
      {
        name: '霍加香妃',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch2.png'),
      },
      {
        name: '博爾特雨蕁',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch3.png'),
      },
      {
        name: '司徒翠',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch4.png'),
      },
      {
        name: '烏拉拉拉京櫻',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch5.png'),
      },
      {
        name: '太后',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch6.png'),
      },
      {
        name: '甄一',
        charTag: '女',
        image: require('../assets/images/stories/00100/ch7.png'),
      },
      {
        name: '文太醫',
        charTag: '男',
        image: require('../assets/images/stories/00100/ch8.png'),
      },
    ],
  },
];